version: 1.0.{build}

branches:
  only:
    - master
    
image: Visual Studio 2019
clone_folder: c:\projects\xenos

platform: 
  - Win32
  - x64
  
configuration: 
  - Release
  
build:
  parallel: true
  project: Xenos.sln
  
artifacts:
  - path: build\Win32\Release\cmd.exe
    name: Release Binary x86
    type: zip
  - path: build\x64\Release\cmd.exe
    name: Release Binary x64
    type: zip